python analyze_nulf_chronological.py --user_threshold 5 --item_threshold 5
python analyze_nulf_chronological.py --user_threshold 2 --item_threshold 5
python analyze_nulf_chronological.py --user_threshold 1 --item_threshold 5
python analyze_nulf_chronological.py --user_threshold 5 --item_threshold 2
python analyze_nulf_chronological.py --user_threshold 2 --item_threshold 2
python analyze_nulf_chronological.py --user_threshold 1 --item_threshold 2
python analyze_nulf_chronological.py --user_threshold 5 --item_threshold 1
python analyze_nulf_chronological.py --user_threshold 2 --item_threshold 1
python analyze_nulf_chronological.py --user_threshold 1 --item_threshold 1